### Get the schema
GET http://localhost:8080/graphql

### Simple Query
GRAPHQL http://localhost:8080/graphql

{
  greeting(name: "George") {
    Greeting
  }
}

### Variable Example
GRAPHQL http://localhost:8080/graphql

query greeting($name: String!) {
  greeting(name: $name) {
    Greeting
  }
}

{
  "name": "George"
}

### Get Widgets
GRAPHQL http://localhost:8080/graphql

query GetWidgets {
  GetWidgets {
    id
    name
    price
    quantity
  }
}

### Get a specific widget
GRAPHQL http://localhost:8080/graphql

query GetWidget($id: ID!) {
  GetWidget(id: $id) {
    id
    name
    price
    quantity
  }
}

{
  "id": 1
}

### Add Widget
GRAPHQL http://localhost:8080/graphql

mutation AddWidget($widget: WidgetInput!) {
  CreateWidget(widget: $widget) {
    id
    name
    price
    quantity
  }
}

{
  "widget": {
    "name": "Widget 42",
    "price": 69.23,
    "quantity": 10
  }
}

### Update Widget
GRAPHQL http://localhost:8080/graphql

mutation UpdateWidget($widget: WidgetInput!) {
  UpdateWidget(widget: $widget) {
    id
    name
    price
    quantity
  }
}

{
  "widget": {
    "id": 1,
    "name": "Widget 42",
    "price": 69.23,
    "quantity": 105
  }
}

### Update Widget - Error case (note the id)
GRAPHQL http://localhost:8080/graphql

mutation UpdateWidget($widget: WidgetInput!) {
  UpdateWidget(widget: $widget) {
    id
    name
    price
    quantity
  }
}

{
  "widget": {
    "id": -1,
    "name": "Widget 42",
    "price": 2.50,
    "quantity": 5
  }
}
